### ISSUE TITLE
e6 docker service doesn't wait until elastic is ready to accept connections

### ISSUE THREAD

**Issue by yggdrasil75** [zwagoth/e621ng#446]
I went ahead and tried to set this up. in the instructions is listed the the default account is admin and e621test, but I tried logging in with that and it did not work. it appears that there are no accounts set up right now at all, how can I either add an admin account from terminal or elevate an account made normally to admin?

**Comment by DonovanDMC** [comment]
The normal setup makes both an admin and auto_moderator account
The latter is vital to functionality
Rerun setup and watch for errors, and make sure you aren't randomly disabling something

As for elevating an account, without one already existing you can't do it through the ui, so just register an account then connect to the database server, and edit the `level` of the account you want to be an admin to **50**

You can see a list of levels and their corresponding numbers [here](https://github.com/zwagoth/e621ng/blob/master/config/danbooru_default_config.rb#L84-L92)

**Comment by yggdrasil75** [comment]
<details>
<summary>
Error Log
</summary>

```
== Preparing search indices ==
/usr/local/lib/ruby/3.1.0/socket.rb:1214:in `__connect_nonblock': Failed to open TCP connection to elastic:9200 (Connection refused - connect(2) for 172.19.0.4:9200) (Faraday::ConnectionFailed)
        from /usr/local/lib/ruby/3.1.0/socket.rb:1214:in `connect_nonblock'
        from /usr/local/lib/ruby/3.1.0/socket.rb:56:in `connect_internal'
        from /usr/local/lib/ruby/3.1.0/socket.rb:137:in `connect'
        from /usr/local/lib/ruby/3.1.0/socket.rb:642:in `block in tcp'
        from /usr/local/lib/ruby/3.1.0/socket.rb:227:in `each'
        from /usr/local/lib/ruby/3.1.0/socket.rb:227:in `foreach'
        from /usr/local/lib/ruby/3.1.0/socket.rb:632:in `tcp'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:998:in `connect'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:976:in `do_start'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:965:in `start'
        from /usr/local/bundle/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:138:in `request_via_get_method'
        from /usr/local/bundle/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:129:in `request_with_wrapped_block'
        from /usr/local/bundle/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:122:in `perform_request'
        from /usr/local/bundle/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:66:in `block in call'
        from /usr/local/bundle/gems/faraday-1.8.0/lib/faraday/adapter.rb:50:in `connection'
        from /usr/local/bundle/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:64:in `call'
        from /usr/local/bundle/gems/faraday-1.8.0/lib/faraday/rack_builder.rb:154:in `build_response'
        from /usr/local/bundle/gems/faraday-1.8.0/lib/faraday/connection.rb:516:in `run_request'
        from /usr/local/bundle/gems/elasticsearch-transport-7.16.1/lib/elasticsearch/transport/transport/http/faraday.rb:50:in `block in perform_request'
        from /usr/local/bundle/gems/elasticsearch-transport-7.16.1/lib/elasticsearch/transport/transport/base.rb:289:in `perform_request'
        from /usr/local/bundle/gems/elasticsearch-transport-7.16.1/lib/elasticsearch/transport/transport/http/faraday.rb:36:in `perform_request'
        from /usr/local/bundle/gems/elasticsearch-transport-7.16.1/lib/elasticsearch/transport/client.rb:197:in `perform_request'
        from /usr/local/bundle/gems/elasticsearch-7.16.1/lib/elasticsearch.rb:92:in `elasticsearch_validation_request'
        from /usr/local/bundle/gems/elasticsearch-7.16.1/lib/elasticsearch.rb:51:in `verify_elasticsearch'
        from /usr/local/bundle/gems/elasticsearch-7.16.1/lib/elasticsearch.rb:40:in `method_missing'
        from /usr/local/bundle/gems/elasticsearch-api-7.16.1/lib/elasticsearch/api/namespace/common.rb:38:in `perform_request'
        from /usr/local/bundle/gems/elasticsearch-api-7.16.1/lib/elasticsearch/api/actions/indices/exists.rb:51:in `block in exists'
        from /usr/local/bundle/gems/elasticsearch-api-7.16.1/lib/elasticsearch/api/utils.rb:217:in `__rescue_from_not_found'
        from /usr/local/bundle/gems/elasticsearch-api-7.16.1/lib/elasticsearch/api/actions/indices/exists.rb:50:in `exists'
        from /usr/local/bundle/gems/elasticsearch-model-7.2.0/lib/elasticsearch/model/indexing.rb:273:in `index_exists?'
        from /usr/local/bundle/gems/elasticsearch-model-7.2.0/lib/elasticsearch/model/indexing.rb:250:in `create_index!'
        from /usr/local/bundle/gems/railties-6.1.6.1/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
        from /usr/local/bundle/gems/railties-6.1.6.1/lib/rails/commands/runner/runner_command.rb:45:in `eval'
        from /usr/local/bundle/gems/railties-6.1.6.1/lib/rails/commands/runner/runner_command.rb:45:in `perform'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/railties-6.1.6.1/lib/rails/command/base.rb:69:in `perform'
        from /usr/local/bundle/gems/railties-6.1.6.1/lib/rails/command.rb:48:in `invoke'
        from /usr/local/bundle/gems/railties-6.1.6.1/lib/rails/commands.rb:18:in `<main>'
        from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
        from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from bin/rails:4:in `<main>'
/usr/local/lib/ruby/3.1.0/socket.rb:1214:in `__connect_nonblock': Failed to open TCP connection to elastic:9200 (Connection refused - connect(2) for 172.19.0.4:9200) (Errno::ECONNREFUSED)
        from /usr/local/lib/ruby/3.1.0/socket.rb:1214:in `connect_nonblock'
        from /usr/local/lib/ruby/3.1.0/socket.rb:56:in `connect_internal'
        from /usr/local/lib/ruby/3.1.0/socket.rb:137:in `connect'
        from /usr/local/lib/ruby/3.1.0/socket.rb:642:in `block in tcp'
        from /usr/local/lib/ruby/3.1.0/socket.rb:227:in `each'
        from /usr/local/lib/ruby/3.1.0/socket.rb:227:in `foreach'
        from /usr/local/lib/ruby/3.1.0/socket.rb:632:in `tcp'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:998:in `connect'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:976:in `do_start'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:965:in `start'
        from /usr/local/bundle/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:138:in `request_via_get_method'
        from /usr/local/bundle/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:129:in `request_with_wrapped_block'
        from /usr/local/bundle/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:122:in `perform_request'
        from /usr/local/bundle/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:66:in `block in call'
        from /usr/local/bundle/gems/faraday-1.8.0/lib/faraday/adapter.rb:50:in `connection'
        from /usr/local/bundle/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:64:in `call'
        from /usr/local/bundle/gems/faraday-1.8.0/lib/faraday/rack_builder.rb:154:in `build_response'
        from /usr/local/bundle/gems/faraday-1.8.0/lib/faraday/connection.rb:516:in `run_request'
        from /usr/local/bundle/gems/elasticsearch-transport-7.16.1/lib/elasticsearch/transport/transport/http/faraday.rb:50:in `block in perform_request'
        from /usr/local/bundle/gems/elasticsearch-transport-7.16.1/lib/elasticsearch/transport/transport/base.rb:289:in `perform_request'
        from /usr/local/bundle/gems/elasticsearch-transport-7.16.1/lib/elasticsearch/transport/transport/http/faraday.rb:36:in `perform_request'
        from /usr/local/bundle/gems/elasticsearch-transport-7.16.1/lib/elasticsearch/transport/client.rb:197:in `perform_request'
        from /usr/local/bundle/gems/elasticsearch-7.16.1/lib/elasticsearch.rb:92:in `elasticsearch_validation_request'
        from /usr/local/bundle/gems/elasticsearch-7.16.1/lib/elasticsearch.rb:51:in `verify_elasticsearch'
        from /usr/local/bundle/gems/elasticsearch-7.16.1/lib/elasticsearch.rb:40:in `method_missing'
        from /usr/local/bundle/gems/elasticsearch-api-7.16.1/lib/elasticsearch/api/namespace/common.rb:38:in `perform_request'
        from /usr/local/bundle/gems/elasticsearch-api-7.16.1/lib/elasticsearch/api/actions/indices/exists.rb:51:in `block in exists'
        from /usr/local/bundle/gems/elasticsearch-api-7.16.1/lib/elasticsearch/api/utils.rb:217:in `__rescue_from_not_found'
        from /usr/local/bundle/gems/elasticsearch-api-7.16.1/lib/elasticsearch/api/actions/indices/exists.rb:50:in `exists'
        from /usr/local/bundle/gems/elasticsearch-model-7.2.0/lib/elasticsearch/model/indexing.rb:273:in `index_exists?'
        from /usr/local/bundle/gems/elasticsearch-model-7.2.0/lib/elasticsearch/model/indexing.rb:250:in `create_index!'
        from /usr/local/bundle/gems/railties-6.1.6.1/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
        from /usr/local/bundle/gems/railties-6.1.6.1/lib/rails/commands/runner/runner_command.rb:45:in `eval'
        from /usr/local/bundle/gems/railties-6.1.6.1/lib/rails/commands/runner/runner_command.rb:45:in `perform'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/railties-6.1.6.1/lib/rails/command/base.rb:69:in `perform'
        from /usr/local/bundle/gems/railties-6.1.6.1/lib/rails/command.rb:48:in `invoke'
        from /usr/local/bundle/gems/railties-6.1.6.1/lib/rails/commands.rb:18:in `<main>'
        from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
        from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from bin/rails:4:in `<main>'
/usr/local/lib/ruby/3.1.0/socket.rb:1214:in `__connect_nonblock': Connection refused - connect(2) for 172.19.0.4:9200 (Errno::ECONNREFUSED)
        from /usr/local/lib/ruby/3.1.0/socket.rb:1214:in `connect_nonblock'
        from /usr/local/lib/ruby/3.1.0/socket.rb:56:in `connect_internal'
        from /usr/local/lib/ruby/3.1.0/socket.rb:137:in `connect'
        from /usr/local/lib/ruby/3.1.0/socket.rb:642:in `block in tcp'
        from /usr/local/lib/ruby/3.1.0/socket.rb:227:in `each'
        from /usr/local/lib/ruby/3.1.0/socket.rb:227:in `foreach'
        from /usr/local/lib/ruby/3.1.0/socket.rb:632:in `tcp'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:998:in `connect'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:976:in `do_start'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:965:in `start'
        from /usr/local/bundle/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:138:in `request_via_get_method'
        from /usr/local/bundle/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:129:in `request_with_wrapped_block'
        from /usr/local/bundle/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:122:in `perform_request'
        from /usr/local/bundle/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:66:in `block in call'
        from /usr/local/bundle/gems/faraday-1.8.0/lib/faraday/adapter.rb:50:in `connection'
        from /usr/local/bundle/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:64:in `call'
        from /usr/local/bundle/gems/faraday-1.8.0/lib/faraday/rack_builder.rb:154:in `build_response'
        from /usr/local/bundle/gems/faraday-1.8.0/lib/faraday/connection.rb:516:in `run_request'
        from /usr/local/bundle/gems/elasticsearch-transport-7.16.1/lib/elasticsearch/transport/transport/http/faraday.rb:50:in `block in perform_request'
        from /usr/local/bundle/gems/elasticsearch-transport-7.16.1/lib/elasticsearch/transport/transport/base.rb:289:in `perform_request'
        from /usr/local/bundle/gems/elasticsearch-transport-7.16.1/lib/elasticsearch/transport/transport/http/faraday.rb:36:in `perform_request'
        from /usr/local/bundle/gems/elasticsearch-transport-7.16.1/lib/elasticsearch/transport/client.rb:197:in `perform_request'
        from /usr/local/bundle/gems/elasticsearch-7.16.1/lib/elasticsearch.rb:92:in `elasticsearch_validation_request'
        from /usr/local/bundle/gems/elasticsearch-7.16.1/lib/elasticsearch.rb:51:in `verify_elasticsearch'
        from /usr/local/bundle/gems/elasticsearch-7.16.1/lib/elasticsearch.rb:40:in `method_missing'
        from /usr/local/bundle/gems/elasticsearch-api-7.16.1/lib/elasticsearch/api/namespace/common.rb:38:in `perform_request'
        from /usr/local/bundle/gems/elasticsearch-api-7.16.1/lib/elasticsearch/api/actions/indices/exists.rb:51:in `block in exists'
        from /usr/local/bundle/gems/elasticsearch-api-7.16.1/lib/elasticsearch/api/utils.rb:217:in `__rescue_from_not_found'
        from /usr/local/bundle/gems/elasticsearch-api-7.16.1/lib/elasticsearch/api/actions/indices/exists.rb:50:in `exists'
        from /usr/local/bundle/gems/elasticsearch-model-7.2.0/lib/elasticsearch/model/indexing.rb:273:in `index_exists?'
        from /usr/local/bundle/gems/elasticsearch-model-7.2.0/lib/elasticsearch/model/indexing.rb:250:in `create_index!'
        from /usr/local/bundle/gems/railties-6.1.6.1/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
        from /usr/local/bundle/gems/railties-6.1.6.1/lib/rails/commands/runner/runner_command.rb:45:in `eval'
        from /usr/local/bundle/gems/railties-6.1.6.1/lib/rails/commands/runner/runner_command.rb:45:in `perform'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/railties-6.1.6.1/lib/rails/command/base.rb:69:in `perform'
        from /usr/local/bundle/gems/railties-6.1.6.1/lib/rails/command.rb:48:in `invoke'
        from /usr/local/bundle/gems/railties-6.1.6.1/lib/rails/commands.rb:18:in `<main>'
        from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
        from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from bin/rails:4:in `<main>'

== Command ["bin/rails r Post.__elasticsearch__.create_index!"] failed ==
ERROR: 1

```

</details>

This error is thrown during setup. appears to be the cause. 

full log: https://gist.github.com/yggdrasil75/5eb4ed4faebb192344986f226661d9f4

**Comment by Earlopain** [comment]
Elasticsearch needs to be up for seeding to work. Run `docker-compose up` before you seed. If that doesn't work just reset your current data with `docker-compose down -v` and `docker-compose build --no-cache` and follow the instructions in the readme again, something might have gone wrong during the image creation.

**Comment by yggdrasil75** [comment]
step 6 has 2 commands, the first is seed and the second is bring up the dockers. if the dockers should be up before seeding, then could the readme be updated to state as much?
I am running the commands now and they appear to have worked, but ordered instructions being in the right order do help.

**Comment by yggdrasil75** [comment]
made [447](https://github.com/zwagoth/e621ng/pull/447) to order commands properly.

**Comment by DonovanDMC** [comment]
> Elasticsearch needs to be up for seeding to work. Run `docker-compose up` before you seed. If that doesn't work just reset your current data with `docker-compose down -v` and `docker-compose build --no-cache` and follow the instructions in the readme again, something might have gone wrong during the image creation.

Running the setup command in the readme should do the seeding for you, no? I know my setup worked just fine, and I ran the commands in the order specified in the readme

**Comment by Earlopain** [comment]
It works, but only if elastic is fully up. When your PC is not quick enough the seeding starts before elastic is ready and seeding fails. It's a race condition.

**Comment by DonovanDMC** [comment]
Ah, I see

**Comment by DonovanDMC** [comment]
If I might ask (from the comments on that pr) why isn't a health check usable? Back when this used vagrant, I rolled my own compose file and had health checks for everything
```
healthcheck:
      interval: 10s
      timeout: 2s
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null
        http://localhost:9200/ || exit 1
```

[here](https://github.com/DonovanDMC/YiffyAPI/blob/master/docker-compose.yml#L129-L149) I've tossed that out the window now but I'm pretty sure that worked

I suppose I may just be assuming accepting connections = ready, which may not be the case, I don't really use elasticsearch myself

**Comment by Earlopain** [comment]
I think my fatal flaw was relying on the provided documentation. I looked at https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on, which is also the first result when googling `docker-compose healthcheck` btw. In hindsight I should have looked at the navbar where it is listed under legacy versions. But then again this is the first sentence on that page

> These topics describe version 3 of the Compose file format. This is the newest version.

> depends_on does not wait for db and redis to be “ready” before starting web - only until they have been started. If you need to wait for a service to be ready, see [Controlling startup order](https://docs.docker.com/compose/startup-order/) for more on this problem and strategies for solving it.

Googling revealed that this feature was once part of the compose specification 2, but removed with 3, then added back again in some later revision. It's documented on https://docs.docker.com/compose/compose-file, so I will see how that works. Thanks for making me look into this.

> I suppose I may just be assuming accepting connections = ready, which may not be the case, I don't really use elasticsearch myself

That's basically how I do it for the testrunner myself, and that seems to work out just fine. https://github.com/zwagoth/e621ng/blob/44796ecb528ab1f87bed61e87913a347855eeafa/docker/test_runner.sh

**Comment by DonovanDMC** [comment]
Using depends_on like so *should* wait until the services health check has passed
```
    depends_on:
      elastic:
        condition: service_healthy
```
